management:
   endpoints:
      web:
         exposure:
            include: "*"

spring:
   h2: 
      console.enabled: true
   jpa:
      spring.jpa.database-platforms: org.hibernate.dialect.H2Dialect
   datasource: 
      url: jdbc:h2:file:/data/demo
      username: root
      password: admin
      driverClassName: org.h2.Driver
           

course:
   message: Mensaje desde desde perfil -> prod
   defaultmessage: Mensaje por defecto	
   
server.port: 8091
