management:
   endpoints:
      web:
         exposure:
            include: "*"
                      
course:
   message: Mensaje desde application
   defaultmessage: Mensaje por defecto	
               
spring.profiles.active: prod

server.port: 8090
